POST http://localhost:3001/user  
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJVc2VySWQiOjJ9.Yvmr8A_AL0W56Gah8pmK0Sn6YifereyRTq1nnNh7Rn8


{"username":"raed5","password":"00000000","role":"EMPLOYEE"}

###
GET http://localhost:3001/user/1

###
PATCH  http://localhost:3001/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJVc2VySWQiOjJ9.Yvmr8A_AL0W56Gah8pmK0Sn6YifereyRTq1nnNh7Rn8

{
    "id": 2,
    "locked": false,
    "username":"raed2",
    "role":"EMPLOYEE"

}

###
GET http://localhost:3001/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJVc2VySWQiOjJ9.Yvmr8A_AL0W56Gah8pmK0Sn6YifereyRTq1nnNh7Rn8

###

GET http://localhost:3001/task/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsInVzZXJuYW1lIjoicmFlZCIsImlhdCI6MTcwNTMxOTIzOSwiZXhwIjoxNzA1MzIxMDM5fQ.kcCe8RVnrSMn0IMC3iYAj3JYAiyg_mpv2zjmcEsE6Ew


###
POST http://localhost:3001/task 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJVc2VySWQiOjR9.DJk7BR_t1IE05CVxBnj1zfPh1wq8Vr9ukpaGBfULf_Y

{"title": "my task "}
 


###
GET http://localhost:3001/notification?perPage=10&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiZW1wbG95ZWUxIiwicm9sZXMiOlsiRU1QTE9ZRUUiXSwiaWF0IjoxNzEwODI3MTQwLCJleHAiOjE3MTA4Mjg5NDB9.JlEagY-DIXakiuJeCW7NLwhYYl5ZC1nzhRxor15I6GA


###
POST http://216.137.181.173:8080/api/v1/users/resetPassword
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJVc2VySWQiOjEsIlJvbGVzIjpbeyJhdXRob3JpdHkiOiJTVVBFUl9BRE1JTiJ9LHsiYXV0aG9yaXR5IjoiTUlOSVNUUllfQURNSU4ifV0sInN1YiI6ImFkbWluIiwiaWF0IjoxNzEzMjQ0NTUyLCJleHAiOjE3MTMzMzA5NTJ9.CDVD3DgBQ5lbfbuF9NXPzHCVOgoD5MMAJSKFTOWVAojEIK7HySWoBQss5CVoAGkXW6OgJ1IURYkifoHL4AqwqjE5JFbkyBAnu_u-VPjG0uXyaHLglaxmuxvi_8dlIlGLq2Be0NN3Tn-ArgUt2GF8bI4QkC_pXsrMj6DbPEfII9OeyvuEIBFOAG2MJ_TaN0H3XQFgUm0gpprhWWmIUjA4yb3IPjCQJ-0D9SI7X54ljq3qcFEdbbbxHC2kvsnZ049ltSnqURzhLQaz2cryhc0RXM9yRSYDVrBdpdIbU5h9o4KVFONpTj1KHtzSLcdIXsAYpvGJg3o7HjpRIhh9Z7VHPg
Content-Type: multipart/form-data

{
    "id": 2,
    "newPassword":"password"
}

